# Generated by Django 4.2.4 on 2023-08-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='trainer name')),
                ('address', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=25, verbose_name='trainer phone')),
                ('email', models.EmailField(max_length=254, verbose_name='trainer email')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Client name')),
                ('dateofjoining', models.DateTimeField(verbose_name='Client doj')),
                ('phonenumber', models.CharField(max_length=120)),
                ('Amountdue', models.CharField(max_length=120)),
                ('clientimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.trainers')),
            ],
        ),
    ]
